### ISSUE TITLE
File Names

### ISSUE THREAD

**Issue by smaragdus** [bobbyrne01/save-text-to-file-chrome#2] opened 2019-09-27 21:50 UTC
I am using **Save text to file** version **2.0** with the following settings for file name, screen:

![Save text to file 2 0 - 2019-09-28 - 002](https://user-images.githubusercontent.com/9025757/65803969-fc86b800-e188-11e9-8e22-a568dbe7d640.png)

yet I always get file names of the following pattern:

`b37fe176-2f13-46fe-91e4-080cd8adc6a7.txt`

`fc4b3534-8ef3-4092-9396-337f4272a813.txt`

which means I have to manually rename all saved text files.

This happens under Windows 8 x64 using [Cent Browser](https://www.centbrowser.com/) ([version](https://www.centbrowser.com/history.html) **3.9.2.45**).

Can you confirm this problem?

**Comment by Dboingue** [comment] 2020-01-07 03:59
same with windows 7 x64 chrome latest 79 ish.

I have had this problem before, maybe it was with a Firefox version, i don't recall.  tried disabling, enabling.  now will try removing reinstall.

This happened today only, yesterday was fine.  2020-01-06

Editing: 2020-02-25, BTW this was not the only extension affected, after uninstalling, deleting extension folder traces and extension setting folder traces, reinstalling, did not help. BUT chrome reset option did.  I can now save without being forced to use uniqueID filenames.

Edit: **Single extension conflict**: I forgot to add, that I found the extension interaction.  Toggling "**download them all**" seems to be equivalent to reset.  Problem and fix reproducible.  all other affected extensions with respect to file naming also have both reproducible.  So I had to choose.  since there is no more bandwidth throttle at any level, I kept this extension here.  and use waterfox or other browser still supporting real user-experience minded extension APIs  not the corset of web extensions (maybe the API is not to blame but the customization avoidance of the modernization visionaries steering its development)

**Comment by bobbyrne01** [comment] 2020-08-20 09:27
Going to close this issue due to recent updates in the extension (4.1.0).

Please retest using latest install instructions here:

https://github.com/bobbyrne01/save-text-to-file-firefox#save-text-to-file-firefox

Or if you prefer Chrome, use:

https://github.com/bobbyrne01/save-text-to-file-chrome#save-text-to-file-chrome

**Closed as completed** 2020-08-20 09:28 UTC

**Comment by smaragdus** [comment] 2020-08-20 15:59
@bobbyrne01 

I tested **Save Text to File** version **2.1.0** with a Chromium-based browser and I still get file names like these:

- 9d6938a0-3dcd-41d1-8358-93432d376c1f.txt
- ab940aa6-71c0-477f-8b2f-01ca0324a883.txt
- d9774fd2-1cc1-45ed-8087-a3fe6d6ec4a3.txt
- f0916a16-f5cf-48ed-907b-44ef22d0aa2b.txt

Uninstalling and reinstalling the extension did not help. I may try the extension with a different Chromium-based browser.

**Comment by bobbyrne01** [comment] 2020-08-20 16:05
Only versions 4 or above are supported.

**Comment by smaragdus** [comment] 2020-08-20 16:22
Well, latest [Chrome version](https://chrome.google.com/webstore/detail/save-text-to-file/mkepenkbhepjelljcfiooignmpfgochi) is **2.1.0** (released on _2020-08-20_) while latest [Firefox version](https://addons.mozilla.org/en-US/firefox/addon/save-text-to-file/) is **4.1.0** (released on _2020-08-06_).

**Comment by bobbyrne01** [comment] 2020-08-20 16:32
My bad, confused the version numbers between browsers.

I tested:
```
Chromium
Version 86.0.4240.0 (Developer Build) (x86_64)
Save Text to File: 2.1.0
```

And text was saved to a file with a correct name:
```
rob@Roberts-MacBook-Pro Downloads % cat 1597940973185-save-text-to-file--.txt 

Wikipedia is a free online encyclopedia, created and edited by volunteers around the world and hosted by the Wikimedia Foundation.
```

**Comment by bobbyrne01** [comment] 2020-08-20 16:34
btw @smaragdus as @Dboingue mentioned, its likely a separate extension in your browser causing this issue. 

On a clean browser with Save Text to File, it functions fine.

**Comment by smaragdus** [comment] 2020-08-20 17:20
@bobbyrne01 

> its likely a separate extension in your browser causing this issue.
> 
> On a clean browser with Save Text to File, it functions fine.

When I have time I will do some more tests (I have several Chromium-based browsers ([Cent](https://www.centbrowser.com/), [Iridium](https://iridiumbrowser.de/), [Vivaldi](https://vivaldi.com/)), which I use in portable mode. I will check your extensions with clean profiles. If it happens that I find something about why file names get corrupted that way I will report it here.

Thank you for maintaining this useful extension!

**Comment by Dboingue** [comment] 2020-08-20 17:27
i only came across one extension of my many in use. it was Download them 
all on chrome.
yes, thanks for this extension.
allows for uninterrupted thought flow while browsing/searching/following 
up ideas, without getting distracted by adding backtracking info manually.

Le 20/08/2020 à 13:20, smaragdus a écrit :

**Comment by Dboingue** [comment] 2021-02-22 17:13
This issue happens again, when using another mass downloader (previous comment of mine was about Downloadthemall.
simple mass downloader, this time. and again disabling that extension, reverts to correct filenaming.

I did not check if the wrong behavior still happens with Download them all. But could there be a pattern?  Was would be common to mass downloaders, that would affect another extension trying to handle filenames typically be.  Why would these extension affect the behavior of another by being enabled (should i try restricting their permission to click only?)... or is some Chrome toggle, that one extension can reach and impose to the the others? i am trying to understand top down.  it might not be helpful. but i wonder nonetheless..

i am not sure that this issue is really closed.  because this is about extensions interactions. it makes it a difficult one, but not a closed one.. i would suggest.

**Comment by OmgImAlexis** [comment] 2021-05-13 02:20
For the devs here is a work around for the issue. Instead of using the chrome download API use this.

```js
const downloadFile = (fileName, blob) => {
    const link = document.createElement('a');
    link.download = filename;
    link.href = URL.createObjectURL(blob, { type: 'text/plain;charset=UTF-8' });
    link.dispatchEvent(new MouseEvent('click'));
    URL.revokeObjectURL(link.href);
}

downloadFile('file.png', blob);
```
